# Generated by Django 3.2.18 on 2023-04-24 16:54

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230422_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.validate_color], verbose_name='Цвет в HEX'),
        ),
    ]
